Open-Acidification/TankController

- .github/workflows/e2e.yaml
- README.md
- tests/test_e2e.py
> Updating e2e tests.

- Open_Acidification_pH-stat_arduino/Open_Acidification_pH-stat_arduino.ino
- Open_Acidification_pH-stat_arduino/loop.ino
Switching to https://semver.org/. I also bumped the number to 0.2.0. I think this is a good starting point for the next release.
> Updating versioning.

- scripts/install_libraries.sh
- scripts/uninstall_libraries.sh
Working on removing unused libraries.
> Removed unused libraries.

- GUI/TankController.py
Let's see how this looks on Ubuntu.
> Update GUI with fewer boxes and more density-independent layout

- test/Blink.cpp
> Remove commented-out code

- GUI/Makefile
- GUI/TankController.py
- GUI/libTC.cpp
Also suppress warnings from other libraries.
> Update GUI for pH Probe (serial port 1)

- src/UIState/SeePIDConstants.cpp
- test/SeePIDConstants.cpp
> PHProbe::instance()->getSlope() returns a String, not a float

- .github/actions/spelling/expect.txt
- .gitignore
- GUI/TankController.py
- GUI/libTC.cpp
- src/Devices/SD_TC.cpp
- src/Devices/SD_TC.h
- src/TankControllerLib.cpp
- src/UIState/MainMenu.h
This allows us to look at the SD data in the GUI simulator.
> Download SD to local file system

- .github/actions/spelling/expect.txt
- src/Devices/SD_TC.cpp
- src/Devices/Serial_TC.cpp
- src/UIState/MainMenu.cpp
- src/UIState/NumberCollectorState.cpp
- src/UIState/SeeDeviceAddress.cpp
- src/UIState/SeeDeviceUptime.cpp
- src/UIState/SeeGoogleMins.cpp
- src/UIState/SeePIDConstants.cpp
- src/UIState/SeeTankID.cpp
- src/UIState/SetGoogleSheetInterval.cpp
- src/UIState/SetKD.cpp
- src/UIState/SetKI.cpp
- src/UIState/SetKP.cpp
- src/UIState/SetPHSetPoint.cpp
- src/UIState/SetTankID.cpp
- src/UIState/SetTempSetPoint.cpp
- test/SeeLogFile.cpp
in reference to https://github.com/Open-Acidification/TankController/issues/65
> Changed all sprintf To snprintf

- src/UIState/MainMenu.cpp
- src/UIState/SetCalibrationClear.cpp
- src/UIState/SetCalibrationClear.h
With the changes to the pH Calibration we need a way to clear the calibration. This is a stub for that functionality.
> SetCalibrationClear stub

- src/Devices/PHControl.cpp
- src/Devices/PHControl.h
- src/UIState/EnablePID.cpp
- src/UIState/EnablePID.h
- test/EnablePID.cpp
* Show changes to flag in serial log
* Add ability to read flag (for testing)
* Add ability to enable/disable PID
* Add tests
> Enable/Disable PID (fix #100)

- src/UIState/MainMenu.cpp
> See google minutes

- .github/actions/spelling/expect.txt
- docs/index.md
- scripts/install_libraries.sh
> Remove AutoTune

- .github/actions/spelling/expect.txt
- src/UIState/SetCalibrationClear.cpp
- src/UIState/SetCalibrationClear.h
- test/SetCalibrationClearTest.cpp
No need to use NumberCollectorState; just use 'A' for accept and 'D' for return to main menu.
> Clear calibration with 'A'

- src/Devices/DateTime_TC.cpp
- src/Devices/EEPROM_TC.cpp
- src/Devices/EthernetServer_TC.cpp
- src/Devices/Ethernet_TC.cpp
- src/Devices/Keypad_TC.cpp
- src/Devices/LiquidCrystal_TC.cpp
- src/Devices/PHControl.cpp
- src/Devices/PHProbe.cpp
- src/Devices/Serial_TC.cpp
- src/Devices/Serial_TC.h
- src/Devices/TempProbe_TC.cpp
- src/Devices/TemperatureControl.cpp
- src/Devices/TemperatureControl.h
- src/TankControllerLib.cpp
- test/Menu.cpp
- test/SetPHSetPoint.cpp
> Flash doesn't play nicely with `sprintf()`

- .github/actions/spelling/expect.txt
- src/Devices/DateTime_TC.cpp
- src/Devices/DateTime_TC.h
- src/Devices/EEPROM_TC.cpp
- src/Devices/Keypad_TC.cpp
- src/Devices/LiquidCrystal_TC.cpp
- src/Devices/PHControl.cpp
- src/Devices/PHControl.h
- src/Devices/PHProbe.cpp
- src/Devices/SD_TC.cpp
- src/Devices/SD_TC.h
- src/Devices/Serial_TC.cpp
- src/Devices/Serial_TC.h
- src/Devices/TempProbe_TC.cpp
- src/Devices/TempProbe_TC.h
- src/Devices/TemperatureControl.cpp
- src/Devices/TemperatureControl.h
- src/TankControllerLib.cpp
- src/UIState/SeeLogFile.cpp
- test/TestDateTime.cpp
- test/TestPHProbe.cpp
- test/TestSD.cpp
- test/TestSeeLogFile.cpp
- test/TestSerial.cpp
- test/TestTCLib.cpp
- test/TestTempProbe_TC.cpp
- test/TestTemperatureCalibration.cpp
* Remove `serialWithTime()` and add `DateTime_TC::printToSerial()`
* Use `Serial.println()` instead of `serial()` during startup
* Changes to pH Probe and Control based on on-device testing
* Temperature should only be read once per second
* Keep all files at root and do not use directories
* All file names should be 8.3 size
* Update some debugging output
> Get things working on the board

- src/Devices/PHControl.cpp
- src/Devices/TemperatureControl.cpp
- src/TankControllerLib.h
- test/TestPHControl.cpp
- test/TestTCLib.cpp
- test/TestTemperatureControl.cpp
Update LOW/HIGH to TURN_SOLENOID_ON/TURN_SOLENOID_OFF in PH and Temperature related functions #125
> Update LOW/HIGH to TURN_SOLENOID_ON/TURN_SOLENOID_OFF

- src/UIState/NumberCollectorState.cpp
- test/SetKPTest.cpp
* Show new value message after saving entered number
* Show number as 32-bit integer rather than as 16-bit integer
> Number collector changes

- GUI/.gitignore
- GUI/Makefile
- GUI/build.sh
- GUI/libTC.cpp
- src/Devices/SD_TC.cpp
- src/Devices/SD_TC.h
* Use python3 explicitly for GUI demo
* Fix problem with opening SD from GUI demo
* Rename `build` to `.build`
> Python GUI changes

- src/Devices/Ethernet_TC.cpp
- src/Devices/PushingBox.cpp
- src/Devices/SD_TC.cpp
- src/TankControllerLib.cpp
- test/PHControlTest.cpp
- test/PushingBoxTest.cpp
- test/SeeDeviceUptimeTest.cpp
- test/SeeVersionTest.cpp
Tests pass and we have seen it push something to the web site!
> PushingBox Support

- src/UIState/SetGoogleSheetInterval.h
- src/UIState/SetKD.h
- src/UIState/SetKI.h
- src/UIState/SetKP.h
- src/UIState/SetTankID.h
- src/UIState/SetTempSetPoint.h
- test/SetGoogleSheetIntervalTest.cpp
- test/SetKDTest.cpp
- test/SetKITest.cpp
- test/SetKPTest.cpp
- test/SetTankIDTest.cpp
- test/SetTempSetPointTest.cpp
return current value for most UI setters.
> Update returnCurrentValue() to return current value

- other/install.sh
- scripts/install_libraries.sh
> Added Double quotes for codacy warnings

- src/Devices/PushingBox.cpp
- src/Devices/PushingBox.h
- test/PushingBoxTest.cpp
> Wait 70 seconds before sending first PushingBox report

- src/Devices/Ethernet_TC.cpp
- src/TankControllerLib.cpp
- src/UIState/MainMenu.cpp
- test/MenuTest.cpp
- test/SeeVersionTest.cpp
- test/TCLibTest.cpp
- Edit menu to use "View Settings" rather than "View TC Settings"
- Update output format for writing to the SD card
- Update test for temperature and pH decimal precision
- Save the DHCP-assigned IP address for later display (fix #185)
- Shorten the Ethernet startup timeout to 5 seconds (fix #170)
- Update version to 21-05-4
> Collection of small changes plus version

- src/Devices/PushingBox.cpp
- src/TankControllerLib.cpp
- src/TankControllerLib.h
- test/PushingBoxTest.cpp
- Write pH and temp to serial port each minute (fix #153)
- Truncate PushingBox request when printing to serial port
> Serial report

- src/UIState/PHCalibration.h
- src/UIState/PHCalibrationHigh.h
- src/UIState/PHCalibrationLow.h
- src/UIState/PHCalibrationMid.h
- test/PHCalibrationMidTest.cpp
> Show current pH during calibration

- scripts/install_libraries.sh
This will give us a better-maintained library with a LGPL 2.1 license.
> Use Keypad `main` rather than `master`

- .github/actions/spelling/allow/SeeDeviceAddressTest.cpp.txt
- src/Devices/LiquidCrystal_TC.cpp
- src/Devices/LiquidCrystal_TC.h
- src/TankControllerLib.cpp
- test/LiquidCrystalTest.cpp
- test/SeeDeviceAddressTest.cpp
- test/SeeVersionTest.cpp
- test/SetTimeTest.cpp
> Generic splash screen

- src/UIState/MainMenu.cpp
- src/UIState/MainMenu.h
With 'Time' we don't need 'Uptime'.
> Remove duplicate menu option

- .arduino-ci.yml
- .github/actions/spelling/expect.txt
- GUI/Makefile
- scripts/install_libraries.sh
- src/Devices/Ethernet_TC.cpp
- src/Devices/Ethernet_TC.h
- src/Devices/SD_TC.cpp
- src/Devices/SD_TC.h
- test/SDTest.cpp
- test/TCLibTest.cpp
> Use SdFat library

- .github/actions/spelling/expect.txt
- README.md
- docs/libraries.md
> Identify libraries and licenses

- library.properties
- src/Devices/EthernetServer_TC.h
- src/Devices/Ethernet_TC.cpp
- src/Devices/Ethernet_TC.h
- src/Devices/PushingBox.cpp
- src/Devices/SD_TC.h
- src/TankControllerLib.cpp
- src/UIState/MainMenu.cpp
- test/EthernetTest.cpp
- test/LiquidCrystalTest.cpp
- test/PushingBoxTest.cpp
- test/SeeVersionTest.cpp
> Disable PushingBox if DHCP failed

- scripts/testAndBuild.sh
In essence, it will force us to review the change and adjust this test if we want to allow the memory use.
> Check for a drop in free space

- src/Devices/PHProbe.cpp
- src/Devices/TempProbe_TC.cpp
- test/PHControlTest.cpp
- test/PHProbeTest.cpp
- test/TemperatureCalibrationTest.cpp
> Record changes to calibration to serial (and SD log)

- README.md
The install process is much simpler!
> Update README.md to remove discussion of floating-point printing

- size.txt
- src/Devices/EthernetServer_TC.cpp
- src/TankController.cpp
- test/EthernetServerTest.cpp
- test/JSONBuilderTest.cpp
- test/LiquidCrystalTest.cpp
- test/SeeVersionTest.cpp
* Enable CORS
* Update to v22.03.2
> Allow sharing our data with other sites

- .github/workflows/Arduino-CI.yaml
- docs/libraries.md
- scripts/install_libraries.sh
- scripts/testAndBuild.sh
- size.txt
- src/Devices/EthernetServer_TC.cpp
- src/UIState/SeeDeviceAddress.h
- src/UIState/SeeDeviceUptime.h
- src/UIState/SeeFreeMemory.h
- src/UIState/SeeGoogleMins.h
- src/UIState/SeeLogFile.h
- src/UIState/SeePHSlope.h
- src/UIState/SeePIDConstants.h
- src/UIState/SeeTankID.h
- src/UIState/SeeTempCalOffset.h
- src/UIState/SeeVersion.h
> Update to latest libraries

- library.properties
- src/TankController.cpp
- test/EthernetServerTest.cpp
- test/JSONBuilderTest.cpp
- test/LiquidCrystalTest.cpp
- test/SeeVersionTest.cpp
Prior commit didn't update library.properties.
> Update version number to 22.07.2 (fix #323)

- .github/workflows/buildWeb.yml
- extras/webClient/lib/components/app_drawer.dart
- extras/webClient/lib/model/app_data.dart
- src/Devices/DateTime_TC.h
- src/Devices/EthernetServer_TC.cpp
- src/Devices/EthernetServer_TC.h
- src/Devices/Keypad_TC.h
- src/Devices/LiquidCrystal_TC.h
- src/Devices/SD_TC.cpp
- src/Devices/Serial_TC.cpp
- src/Devices/TempProbe_TC.h
- src/TC_util.h
- src/TankController.cpp
- src/UIState/NumberCollectorState.h
* Replace `MOCK_PINS_COUNT` with `ARDUINO_CI_COMPILATION_MOCKS`
* Lint spacing
> Rename CI macro

- .github/workflows/buildWeb.yml
- .github/workflows/flutterTests.yml
> Update Flutter actions

- Gemfile
- extras/webClient/pubspec.lock
- src/TC_util.cpp
- test/EthernetServerTest.cpp
* Bump Dart version
* Better variable names
* Combine variable definition with initialization
* Add commented-out arduino_ci options
> Cleanup & refactoring

- src/Devices/EthernetServer_TC.cpp
- src/Devices/EthernetServer_TC.h
- test/EthernetServerTest.cpp
This way you don't need to remember or find https://open-acidification.github.io/TankControllerManager/.
> Redirect to the web UI on "GET /" request

- test/EthernetServerTest.cpp
This doesn't really fix #331, but it adds tests that fail to recreate the issue.
> Test output of fraction for Kp, Ki, and Kd (fix #331)

- extras/web_client/lib/view/current_data_page.dart
- src/Devices/JSONBuilder.cpp
- test/EthernetServerTest.cpp
- test/JSONBuilderTest.cpp
- test/PHControlTest.cpp
It seems that the Arduino has issues when converting large floating point numbers to integers. This appears to fix #331.
> Fix float to int conversion

- extras/scripts/pre-commit
- extras/web_client/lib/model/app_data.dart
- extras/web_client/lib/model/version.dart
- extras/web_client/lib/view/current_data_page.dart
- src/Version.h
> Show problem with bad Json

- Gemfile
- Makefile
- extras/web_client/lib/model/version.dart
- src/Version.h
PR #415 disabled the use of Makefile and this adds it back.
> Update Makefile for recent changes

- extras/web_client/lib/model/version.dart
- src/Devices/DataLogger_TC.cpp
- src/Version.h
- test/PushingBoxTest.cpp
Now it does only one operation per loop (and adjust tests).
> Revert change to DataLogger_TC::loop()

- extras/device_client/lib/model/version.dart
- src/Version.h
- src/model/DataLogger.cpp
- src/model/DataLogger.h
- src/wrappers/Serial_TC.h
- src/wrappers/ThermalProbe_TC.cpp
- src/wrappers/ThermalProbe_TC.h
- test/PHControlTest.cpp
- test/PHProbeTest.cpp
- test/ThermalControlTest.cpp
- test/ThermalProbe_TCTest.cpp
* Make `buffer` a private variable for DataLogger and Serial
* Add mean and standard deviation to ThermalProbe
> Refactor 2 for event log reporting

- .github/workflows/device-controller.yaml
- Makefile
- extras/device_client/lib/model/version.dart
- src/Version.h
I'm investigating the Ansible-CI failures in a separate issue (#451).
> Don't sanatize addresses addresses

- extras/device_client/README.md
- extras/device_client/lib/components/display.dart
- extras/device_client/lib/model/version.dart
- src/Version.h
> Fix display problem

- extras/device_client/lib/model/version.dart
- src/Version.h
- src/wrappers/ThermalProbe_TC.cpp
- src/wrappers/ThermalProbe_TC.h
When I went back to look at the code I saw what was missing when I moved the Statistic variable from the .cpp to the .h file.
> Statistic variable moved to header

- .github/workflows/device-client.yaml
- .github/workflows/log_file_client.yaml
- .github/workflows/log_file_server.yaml
- Makefile
- extras/device_client/lib/model/version.dart
- src/TankController.cpp
- src/Version.h
- src/model/PHControl.cpp
- src/model/PHControl.h
- src/model/PHProbe.cpp
- src/model/RemoteLogPusher.cpp
- src/model/RemoteLogPusher.h
- src/wrappers/EEPROM_TC.cpp
- src/wrappers/SD_TC.cpp
- src/wrappers/SD_TC.h
- test/DateTimeTest.cpp
- test/EthernetServerTest.cpp
- test/RemoteLogPusherTest.cpp
Move more of the alerts branch into main.
> Early January Refactoring
