.github/actions/spelling/excludes.txt, .gitignore, other/README.md, other/arduino_ci.rb, other/cpp_library.rb, other/install.sh, scripts/install_libraries.sh
See https://github.com/Arduino-CI/arduino_ci/pull/294.
=> Add option to speed up local tests

GUI/libTC.cpp, src/UIState/SeeDeviceUptime.cpp
Fix #84. Calculation of offset between host and Arduino mock was wrong and has been fixed. Also, we don't need the `floor()` function (which returns a float) when we are doing integer division.
=> Fix time display for GUI

src/Devices/PHControl.cpp, src/Devices/PHControl.h, src/TankControllerLib.cpp, src/UIState/MainMenu.cpp, src/UIState/SetPHSetPoint.cpp, test/PHControlTest.cpp, test/SetPHSetPoint.cpp
* Update pH control each loop
* Refactor PHControl
* use a singleton
* save and retrieve target in EEPROM
* add some debugging
* MainMenu idle loop now shows actual pH target
* SetPHSetPoint UI State now assigns to PHControl singleton instead of EEPROM
* Update tests to match new design
=> Refactor pH Control

.github/actions/spelling/expect.txt, src/TankControllerLib.cpp, src/TankControllerLib.h, src/UIState/SeeDeviceUptime.cpp, src/UIState/SeeDeviceUptime.h, test/Menu.cpp, test/SeeDeviceUptime.cpp, test/TCLibTest.cpp, test/TempProbe_TC_Test.cpp
Also, don't return to idle menu after 60 seconds.
=> Stop control when doing calibration (fix #102)

src/Devices/PHProbe.cpp, test/PHProbeTest.cpp
=> Don't trim last character read from stream unless it is a '\r'

src/Devices/PHProbe.cpp, src/Devices/PHProbe.h, test/PHProbeTest.cpp, test/SeePHSlopeTest.cpp
=> Show pH Probe slope

.github/actions/spelling/expect.txt, src/Devices/Serial_TC.cpp, src/Devices/TemperatureControl.cpp, src/Devices/TemperatureControl.h, src/UIState/MainMenu.cpp, test/MenuTest.cpp, test/TemperatureControlTest.cpp
Lowercase 'h' or 'c' means turned off while uppercase 'H' or 'C' means turned on.
=> Show temperature control in idle screen

src/Devices/PHProbe.cpp, test/PHControlTest.cpp
So bubbler isn't on continually.
=> Trigger a reset if the pH goes below 7.0

README.md, library.properties
We have badges that point to the (archived) TankControllerLib project (fix #237).
=> Point to TankController project

src/TankControllerLib.cpp
This was noticed when uploading the application to the device.
=> Fix compiler warning when doing free space calculations

src/Devices/Ethernet_TC.cpp, test/PushingBoxTest.cpp
* Skip `Ethernet.maintain()` if we did not get an IP address.
* Changes to PushingBox based on changes to Ethernet library.
=> Update for changes to Ethernet library

src/Devices/PHProbe.cpp
Zero is common on a device with no probe attached.
=> Don't reset just because pH is zero 

.github/actions/spelling/expect.txt, src/Devices/EthernetServer_TC.cpp, src/Devices/EthernetServer_TC.h, src/Devices/PushingBox.cpp, src/Devices/PushingBox.h, src/Devices/SD_TC.cpp, src/Devices/Serial_TC.cpp, src/TankControllerLib.cpp, src/TankControllerLib.h, src/UIState/SeeFreeMemory.cpp, test/EthernetServerTest.cpp
This supports `/echo?key="value"` requests and `/path` requests. Large files take a long time to transfer. Following are some measurements of time with different buffer sizes:
```
Buffer size: 128
file "/20210827.csv" has a size of 5713467
write = 5713467; freeMemory = 4640
timeInRead = 27661; timeInWrite = 79832; timeInFlush = 43
Buffer size: 2048
file "/20210827.csv" has a size of 5858009
write = 5858009; freeMemory = 2720
timeInRead = 11681; timeInWrite = 74739; timeInFlush = 3
Buffer size: 1024
file "/20210827.csv" has a size of 5878029
write = 5878029; freeMemory = 3744
timeInRead = 15108; timeInWrite = 72649; timeInFlush = 3
```
The entire process is blocking so there is a risk of leaving the bubbler on for minutes. Thus, the reading files feature should be considered a basic …
=> Support basic HTTP get file request

.github/actions/spelling/expect.txt, scripts/testAndBuild.sh, src/Devices/EthernetServer_TC.cpp, src/Devices/EthernetServer_TC.h, src/Devices/PHControl.cpp, src/Devices/PHProbe.cpp, src/Devices/PID_TC.cpp, src/Devices/PushingBox.cpp, src/Devices/Serial_TC.cpp, src/Devices/Serial_TC.h, src/Devices/TempProbe_TC.cpp, src/Devices/TemperatureControl.cpp, src/TankControllerLib.cpp, src/UIState/MainMenu.cpp, src/UIState/PHCalibrationHigh.cpp, src/UIState/PHCalibrationLow.cpp, src/UIState/PHCalibrationMid.cpp, src/UIState/SeePIDConstants.cpp, src/UIState/SetKD.cpp, src/UIState/SetKI.cpp, src/UIState/SetKP.cpp, src/UIState/SetPHSetPoint.cpp, src/UIState/SetTempSetPoint.cpp, src/UIState/TemperatureCalibration.cpp, test/PIDTest.cpp
=> Stop using %f for printing floats

.github/workflows/Arduino-CI.yaml, .gitignore, scripts/testAndBuild.sh, size.txt
The arduino_ci test updates `size.txt` when it builds the sketch. Thus each commit will include the current values (if the tests are run!). You can see the new size by viewing the modified files. To ensure that the tests are run before a PR, part of the GitHub action is to update the file and see if it changes. See [here](https://github.com/jgfoster/TankController/runs/3518130868?check_suite_focus=true) for a sample failure.
Fix #139.
=> Include size report with each PR

.github/workflows/lint.yaml
This should avoid the error we get now that the name is a duplicate. See #255.
=> Change Arduino Library Lint to recognize we are in the public library listing

Gemfile, scripts/install.sh, scripts/install_libraries.sh, scripts/test.sh, scripts/testAndBuild.sh, size.txt
Now that it supports the faster testing process we can go back to the primary source.
=> Switch from jgfoster to Arduino-CI for testing

.github/actions/spelling/expect.txt, scripts/test.sh, scripts/testAndBuild.sh
Some things we added to our `testAndBuild.sh` script caused it to fail to report the errors.
=> Ensure that error gets reported back to arduino_ci

.github/actions/spelling/expect.txt, size.txt, test/SeeFreeMemoryTest.cpp, test/SetTimeTest.cpp
Fixes an error in free memory when running test suite on different location (GitHub vs code.cs)
Fixes an error where the rtc on Tank Controller was not being updated before the state was changed.
=> Fix test failures on code.cs

src/UIState/MainMenu.cpp, test/SetPHSetPointTest.cpp
A pH of 10.000 or more does not print nicely in a space formatted for 5.3.
=> Fix buffer overrun problem

size.txt, src/TankController.cpp
Starts the WDT after printing serial messages in case additional messages that take longer than the WDT failsafe are inserted later.
Removes the printout of the root directory of the SD card.
=> Fix WDT hanging too long on setup

src/UIState/SeeDeviceAddress.cpp
When viewing the device address (then reset to enable it).
=> Press '#' to disable the Watchdog Timer

src/Devices/EthernetServer_TC.cpp, src/Devices/EthernetServer_TC.h, src/Devices/LiquidCrystal_TC.cpp, src/Devices/SD_TC.cpp, src/TankController.cpp, src/TankController.h, src/UIState/MainMenu.cpp, src/UIState/MainMenu.h
MainMenu's `idle()` function was calculating values every loop instead of every second, so now `TankController::loop()` executes in 2-4 ms at MainMenu idle.
This also has comments that document experimental speeds for reading from the SD card and writing to the client, in cases for handling file transfer.
This also refactors the file transfer protocol to be non-blocking and is transmitted as multipart data rather than text.
=> Fix MainMenu excess code; add tests for read/write speeds

library.properties, src/Devices/EthernetServer_TC.cpp, src/Devices/EthernetServer_TC.h, src/Devices/SD_TC.cpp, src/Devices/SD_TC.h, src/TankController.cpp, test/EthernetServerTest.cpp, test/JSONBuilderTest.cpp, test/LiquidCrystalTest.cpp, test/SeeVersionTest.cpp
This fixes some issues with HTTP headers for file transfers and for rootdir(). For the rootdir() HTTP header, the size of the body is calculated in advance by counting the number of files in the root directory on the SD card.
=> Listing files with valid HTTP header

library.properties, size.txt, src/Devices/EthernetServer_TC.cpp, src/Devices/EthernetServer_TC.h, src/Devices/SD_TC.cpp, src/Devices/SD_TC.h, src/TankController.cpp, test/EthernetServerTest.cpp, test/JSONBuilderTest.cpp, test/LiquidCrystalTest.cpp, test/SeeVersionTest.cpp
- New HTTP response codes: 404 (not found), 405 (not permitted), 408 (timeout), 500 (internal server error)
- Consolidate HTTP response functions for codes other than 200.
- New connections with no request remain open for 5 seconds before timing out with 408 response. Includes a test.
- If the root directory on the SD card fails to open during rootdir(), a 500 response is sent to the client and the state is reset.
- If EthernetServer_TC's loop() encounters an unknown state (due to programmer error), a 500 response is sent to the client and the state is reset.
- New state COUNTING_FILES replaces boolean isDoneCountingFiles.
- New test: GET request that receives 404 Not Found response
- New test: OPTIONS request that receives 405 Method Not Allowed response
- New test: FOO request that …
=> Ethernet: More HTTP response codes

src/UIState/MainMenu.cpp
Show only two digits after decimal.
=> Avoid buffer overrun if pH is >= 10

src/Devices/JSONBuilder.cpp
Changed from `PIDStatus` to `pidStatus` to use lowercase initial character on local variable name.
=> Change case for local variable name

extras/scripts/build.sh, extras/scripts/testAndBuild.sh, src/Devices/DateTime_TC.cpp, src/Devices/EthernetServer_TC.cpp, src/Devices/EthernetServer_TC.h, src/Devices/LiquidCrystal_TC.cpp, src/Devices/PHProbe.cpp, src/Devices/SD_TC.cpp, src/Devices/SD_TC.h, src/Devices/TemperatureControl.cpp, src/TC_util.cpp, src/TC_util.h, src/TankController.cpp, src/UIState/PHCalibrationHigh.cpp, src/UIState/PHCalibrationLow.cpp, src/UIState/PHCalibrationMid.cpp, test/StringsTest.cpp
Prior usage was `const char *` which is equivalent to `PGM_P` so we don't catch errors with SRAM vs FLASH. By using __Flash_StringHelper (a class), the compiler should catch more errors.
=> Refactor `strscpy_P` to use `__FlashStringHelper *`

extras/webClient/analysis_options.yaml, extras/webClient/lib/components/app_drawer.dart, extras/webClient/lib/components/display.dart, extras/webClient/lib/components/keypad.dart, extras/webClient/lib/model/app_data.dart, extras/webClient/lib/view/files_page.dart, extras/webClient/lib/view/information_page.dart, extras/webClient/pubspec.yaml, extras/webClient/test/app_data_test.dart
Added more rules to the linter and fixed any errors they caught.
=> Lint update

examples/TankController/TankController.ino, src/Devices/PushingBox.cpp, src/Devices/PushingBox.h, src/TC_util.cpp, src/TC_util.h, test/PushingBoxTest.cpp
This can reduce the noise to serial when we are working with a test device.
=> Don't call PushingBox if there is not a device identifier

src/UIState/MainMenu.cpp, src/UIState/PHCalibrationLow.cpp, src/UIState/PHCalibrationMid.cpp, src/UIState/UIState.cpp
While technically correct, it is not necessary to cast a subclass as a superclass when that is what the method expects.
=> Remove `static_cast<>()` from `setNextState()`

Makefile, extras/scripts/post-commit, extras/scripts/pre-commit, extras/scripts/test.sh, extras/scripts/testAndBuild.sh, extras/web_client/lib/components/app_drawer.dart, extras/web_client/lib/model/version.dart, src/Devices/LiquidCrystal_TC.cpp, src/TankController.cpp, src/Version.h, test/EthernetServerTest.cpp, test/JSONBuilderTest.cpp, test/LiquidCrystalTest.cpp, test/SeeVersionTest.cpp
This adds pre-commit and post-commit scripts to the scripts directory. These scripts are copied to `.git/hooks` by the test.sh and testAndBuild.sh scripts where they are run automatically. 
Before a commit the code uses `git describe --tags` to get a version description. This version description is then placed in two files, `src/Version.h` and `extras/web_client/lib/model/version.dart`. The code then uses these files as the version to display on the device and in the web client (at the bottom of the drawer).
We have a self-referential problem: To put the version in a file that is part of version control, it must be edited before a commit. But the description give by Git will be of the status before the commit (or a description of the _prior_ commit) and we really want to have the version …
=> Use Git commit hooks to get version

extras/web_client/lib/components/app_drawer.dart, extras/web_client/lib/components/keypad.dart, extras/web_client/lib/components/nav_bar.dart, extras/web_client/lib/main.dart, extras/web_client/lib/model/app_data.dart, extras/web_client/lib/model/tc_interface.dart, extras/web_client/lib/model/version.dart, extras/web_client/lib/view/current_data_page.dart, extras/web_client/test/app_data_test.dart, extras/web_client/test/tc_interface_test.dart, extras/web_client/test/widget_test.dart, src/Version.h
We were using a property getter for a singleton that starts out as null, so the type was simply Object. By switching to a method getter we can specify the type as not null and this provides better type information (and highlights several "discarded futures" problems that already exist and should be addressed in the future).
=> Ensure type is known for AppData and TcInterface singletons

extras/device_client/lib/model/version.dart, extras/scripts/build.sh, extras/scripts/testAndBuild.sh, src/TankController.cpp, src/Version.h, src/model/RemoteLogPusher.cpp, src/model/RemoteLogPusher.h, src/wrappers/SD_TC.cpp, src/wrappers/SD_TC.h, test/PushingBoxTest.cpp, test/RemoteLogPusherTest.cpp, test/SDTest.cpp
The SD card seems to support only 8.3 names so we should not use the provided filename on local storage. Instead of storing it with the SD wrapper, we now store it with the RemoteLogPusher class.
=> Remote log name
